import json

from usagetrim.core.diff_slimmer import slim_git_diff
from usagetrim.core.lockfile import (
    extract_lockfile_diff_delta,
    is_lockfile,
    summarize_lockfile,
)
from usagetrim.metrics.tokenizer import count_tokens


def test_is_lockfile():
    assert is_lockfile("package-lock.json")
    assert is_lockfile("/foo/bar/Cargo.lock")
    assert is_lockfile("uv.lock")
    assert is_lockfile("poetry.lock")
    assert is_lockfile("pnpm-lock.yaml")
    assert is_lockfile("yarn.lock")
    assert is_lockfile("go.sum")
    assert not is_lockfile("package.json")
    assert not is_lockfile("Cargo.toml")
    assert not is_lockfile("main.py")


def test_summarize_package_lock_json():
    npm_lock = {
        "name": "my-app",
        "version": "1.0.0",
        "lockfileVersion": 3,
        "packages": {
            "": {
                "name": "my-app",
                "version": "1.0.0",
                "dependencies": {
                    "express": "^4.19.2",
                    "zod": "^3.23.8",
                },
                "devDependencies": {
                    "typescript": "^5.4.5",
                },
            },
            "node_modules/express": {
                "version": "4.19.2",
                "resolved": "https://registry.npmjs.org/express/-/express-4.19.2.tgz",
                "integrity": "sha512-abc",
                "dependencies": {
                    "accepts": "~1.3.8",
                },
            },
            "node_modules/zod": {
                "version": "3.23.8",
                "resolved": "https://registry.npmjs.org/zod/-/zod-3.23.8.tgz",
                "integrity": "sha512-def",
            },
            "node_modules/typescript": {
                "version": "5.4.5",
                "resolved": "https://registry.npmjs.org/typescript/-/typescript-5.4.5.tgz",
                "integrity": "sha512-ghi",
            },
            "node_modules/accepts": {
                "version": "1.3.8",
                "resolved": "https://registry.npmjs.org/accepts/-/accepts-1.3.8.tgz",
                "integrity": "sha512-jkl",
            },
        },
    }
    raw = json.dumps(npm_lock, indent=2)

    # General summary
    summary = summarize_lockfile(raw, "package-lock.json")
    assert "package-lock.json" in summary
    assert "express: 4.19.2" in summary
    assert "zod: 3.23.8" in summary
    assert "typescript: 5.4.5" in summary
    assert "3 direct, 4 total packages" in summary

    # Single package query via symbol
    query_res = summarize_lockfile(raw, "package-lock.json", query_package="zod")
    assert "package 'zod'" in query_res
    assert "3.23.8" in query_res
    assert "express" not in query_res

    # Query non-existent
    not_found = summarize_lockfile(raw, "package-lock.json", query_package="nonexistent")
    assert "not found" in not_found


def test_summarize_cargo_lock():
    cargo_lock = """# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "usagetrim"
version = "0.2.0"
dependencies = [
 "anyhow",
 "serde",
]

[[package]]
name = "anyhow"
version = "1.0.86"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "b3d1d046238990b9cf5bcde22a3fb3584ee5cf65fb2765f454ed428c7a0063da"

[[package]]
name = "serde"
version = "1.0.203"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "72561c5ddf481a82abb5b7713fbc98eb4705008ef588245b598b074a16ed9c7c"
"""
    summary = summarize_lockfile(cargo_lock, "Cargo.lock")
    assert "Cargo.lock" in summary
    assert "3 packages locked" in summary
    assert "usagetrim: 0.2.0" in summary
    assert "anyhow: 1.0.86" in summary
    assert "serde: 1.0.203" in summary

    # Query package
    query_res = summarize_lockfile(cargo_lock, "Cargo.lock", query_package="serde")
    assert "package 'serde'" in query_res
    assert "1.0.203" in query_res
    assert "anyhow" not in query_res


def test_summarize_uv_lock():
    uv_lock = """version = 1
revision = 1

[[package]]
name = "fastapi"
version = "0.111.0"
source = { registry = "https://pypi.org/simple" }
dependencies = [
    { name = "pydantic" },
    { name = "starlette" },
]

[[package]]
name = "pydantic"
version = "2.7.1"
source = { registry = "https://pypi.org/simple" }
"""
    summary = summarize_lockfile(uv_lock, "uv.lock")
    assert "uv.lock" in summary
    assert "2 packages locked" in summary
    assert "fastapi: 0.111.0" in summary
    assert "pydantic: 2.7.1" in summary

    query_res = summarize_lockfile(uv_lock, "uv.lock", query_package="fastapi")
    assert "package 'fastapi'" in query_res
    assert "0.111.0" in query_res


def test_lockfile_diff_delta():
    diff_lines = [
        "--- a/package-lock.json",
        "+++ b/package-lock.json",
        '-    "node_modules/zod": {',
        '-      "version": "3.22.0"',
        '+    "node_modules/zod": {',
        '+      "version": "3.23.8"',
        '+    "node_modules/express": {',
        '+      "version": "4.19.2"',
        '-    "node_modules/left-pad": {',
        '-      "version": "1.3.0"',
    ]
    delta = extract_lockfile_diff_delta(diff_lines, "package-lock.json")
    assert "~ zod (3.22.0 -> 3.23.8)" in delta
    assert "+ express@4.19.2" in delta
    assert "- left-pad@1.3.0" in delta


def test_slim_git_diff_with_lockfile_delta():
    raw_diff = """diff --git a/package-lock.json b/package-lock.json
index 1111..2222 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -10,6 +10,12 @@
-    "node_modules/zod": {
-      "version": "3.22.0"
+    "node_modules/zod": {
+      "version": "3.23.8"
+    "node_modules/express": {
+      "version": "4.19.2"
diff --git a/src/main.ts b/src/main.ts
index 3333..4444 100644
--- a/src/main.ts
+++ b/src/main.ts
@@ -1,3 +1,3 @@
-const a = 1;
+const a = 2;
"""
    slimmed = slim_git_diff(raw_diff)
    assert "lockfile delta:" in slimmed
    assert "~ zod (3.22.0 -> 3.23.8)" in slimmed
    assert "+ express@4.19.2" in slimmed
    assert "const a = 2;" in slimmed


def test_large_lockfile_token_reduction():
    # Simulate a 1,000 package lockfile
    pkgs = {"": {"dependencies": {f"pkg-{i}": f"1.{i}.0" for i in range(50)}}}
    for i in range(500):
        pkgs[f"node_modules/pkg-{i}"] = {
            "version": f"1.{i}.0",
            "resolved": f"https://registry.npmjs.org/pkg-{i}/-/pkg-{i}-1.{i}.0.tgz",
            "integrity": f"sha512-dummyhash{i}1234567890abcdef",
        }
    large_json = json.dumps({"packages": pkgs}, indent=2)
    raw_tokens = count_tokens(large_json).claude
    summary = summarize_lockfile(large_json, "package-lock.json")
    summary_tokens = count_tokens(summary).claude

    # Should achieve > 90% reduction
    assert summary_tokens < raw_tokens * 0.10
    assert "50 direct, 500 total packages" in summary


def test_usagetrim_read_lockfile_mcp(tmp_path):
    from usagetrim.mcp.server import handle_usagetrim_read

    lock_file = tmp_path / "package-lock.json"
    npm_lock = {
        "name": "sample",
        "lockfileVersion": 3,
        "packages": {
            "": {"dependencies": {"react": "^18.3.1"}},
            "node_modules/react": {"version": "18.3.1"},
        },
    }
    lock_file.write_text(json.dumps(npm_lock, indent=2))

    # Read without bounds should auto-summarize
    res = handle_usagetrim_read({"path": str(lock_file)})
    assert "react: 18.3.1" in res
    assert "package-lock.json" in res

    # Read with symbol
    sym_res = handle_usagetrim_read({"path": str(lock_file), "symbol": "react"})
    assert "package 'react'" in sym_res
    assert "18.3.1" in sym_res
