from usagetrim.core.diff_slimmer import slim_git_diff

SAMPLE_DIFF = """diff --git a/src/main.py b/src/main.py
index 1234567..89abcdef 100644
--- a/src/main.py
+++ b/src/main.py
@@ -10,6 +10,7 @@ def process():
     context_line_1
     context_line_2
     context_line_3
+    new_important_logic()
     context_line_4
     context_line_5
diff --git a/uv.lock b/uv.lock
index aaaaaaa..bbbbbbb 100644
--- a/uv.lock
+++ b/uv.lock
@@ -1,500 +1,500 @@
-old_package_version = "1.0.0"
+new_package_version = "1.0.1"
""" + "\n".join([f"+ extra_lock_line_{i}" for i in range(100)])


def test_slim_git_diff_folds_lockfile():
    slimmed = slim_git_diff(SAMPLE_DIFF)
    assert "diff --git a/src/main.py b/src/main.py" in slimmed
    assert "+    new_important_logic()" in slimmed
    # Lockfile lines should be folded
    assert "diff --git a/uv.lock b/uv.lock" in slimmed
    assert "lines of lockfile/generated diff omitted by usagetrim" in slimmed
    assert "+ extra_lock_line_50" not in slimmed


def test_slim_git_diff_folds_go_sum_and_snapshots():
    diff = """diff --git a/go.sum b/go.sum
index 1111111..2222222 100644
--- a/go.sum
+++ b/go.sum
@@ -1,100 +1,100 @@
+github.com/gin-gonic/gin v1.9.1 h1:xxxx
diff --git a/tests/__snapshots__/render.snap b/tests/__snapshots__/render.snap
index 3333333..4444444 100644
--- a/tests/__snapshots__/render.snap
+++ b/tests/__snapshots__/render.snap
@@ -1,50 +1,50 @@
+snap line 1
diff --git a/pkg/service.pb.go b/pkg/service.pb.go
index 5555555..6666666 100644
--- a/pkg/service.pb.go
+++ b/pkg/service.pb.go
@@ -1,200 +1,200 @@
+// Code generated by protoc-gen-go. DO NOT EDIT.
+type Message struct {}
+"""
    slimmed = slim_git_diff(diff)
    assert "diff --git a/go.sum b/go.sum" in slimmed
    assert (
        "diff --git a/tests/__snapshots__/render.snap b/tests/__snapshots__/render.snap" in slimmed
    )
    assert "diff --git a/pkg/service.pb.go b/pkg/service.pb.go" in slimmed
    assert "lines of lockfile/generated diff omitted" in slimmed
    assert "Code generated by protoc-gen-go" not in slimmed


def test_slim_git_diff_custom_extra_patterns():
    diff = """diff --git a/fixtures/mock_data.json b/fixtures/mock_data.json
index 1111111..2222222 100644
--- a/fixtures/mock_data.json
+++ b/fixtures/mock_data.json
@@ -1,50 +1,50 @@
+{"id": 1}
+"""
    # Without extra patterns, mock_data.json is kept
    normal = slim_git_diff(diff)
    assert '+{"id": 1}' in normal

    # With extra pattern matching fixtures
    slimmed = slim_git_diff(diff, extra_patterns=[r"fixtures/.*\.json$"])
    assert "diff --git a/fixtures/mock_data.json" in slimmed
    assert "omitted by usagetrim" in slimmed
    assert '+{"id": 1}' not in slimmed
