from __future__ import annotations

import subprocess
from dataclasses import dataclass, field
from pathlib import Path

from usagetrim.metrics.tokenizer import count_tokens

LOCKFILE_NAMES = {
    "package-lock.json",
    "pnpm-lock.yaml",
    "yarn.lock",
    "uv.lock",
    "poetry.lock",
    "Cargo.lock",
    "composer.lock",
    "Gemfile.lock",
}


@dataclass
class FileTokenDelta:
    path: str
    category: str
    tokens_before: int
    tokens_after: int
    delta: int


@dataclass
class PRTokenReport:
    base_ref: str
    total_delta: int = 0
    code_delta: int = 0
    docs_delta: int = 0
    lockfile_delta: int = 0
    other_delta: int = 0
    files: list[FileTokenDelta] = field(default_factory=list)

    def format_markdown(self) -> str:
        sign = "+" if self.total_delta >= 0 else ""
        code_sign = "+" if self.code_delta >= 0 else ""
        docs_sign = "+" if self.docs_delta >= 0 else ""
        lock_sign = "+" if self.lockfile_delta >= 0 else ""

        md = [
            "### Token Impact Report (`usagetrim`)",
            "",
            f"Comparing changes against `{self.base_ref}`:",
            "",
            "| Category | Token Delta |",
            "| :--- | :--- |",
            f"| **Application Code** | `{code_sign}{self.code_delta:,}` tokens |",
            f"| **Documentation & Prompts** | `{docs_sign}{self.docs_delta:,}` tokens |",
            f"| **Dependencies & Lockfiles** | `{lock_sign}{self.lockfile_delta:,}` tokens |",
            f"| **Net Repository Change** | **`{sign}{self.total_delta:,}` tokens** |",
            "",
        ]

        if self.files:
            md.extend(
                [
                    "<details>",
                    "<summary>Top Changed Files by Token Impact</summary>",
                    "",
                    "| File | Category | Delta |",
                    "| :--- | :--- | :--- |",
                ]
            )
            for f in sorted(self.files, key=lambda x: abs(x.delta), reverse=True)[:10]:
                f_sign = "+" if f.delta >= 0 else ""
                md.append(f"| `{f.path}` | {f.category} | `{f_sign}{f.delta:,}` |")
            md.extend(["", "</details>", ""])

        if self.lockfile_delta > 1000:
            md.append(
                "> **Note:** Lockfile bloat in this PR is automatically folded by `usagetrim diff`, "
                "protecting coding agents from context exhaustion."
            )

        md.append(
            "\n*Report generated by [UsageTrim](https://github.com/00200200/usagetrim) — Keep the signal, cut the noise.*"
        )

        return "\n".join(md)


def _get_category(path: str) -> str:
    name = Path(path).name
    if name in LOCKFILE_NAMES:
        return "lockfile"
    suffix = Path(path).suffix.lower()
    if suffix in {".py", ".ts", ".js", ".tsx", ".jsx", ".go", ".rs", ".java", ".c", ".cpp", ".h"}:
        return "code"
    if suffix in {".md", ".rst", ".txt", ".adoc"}:
        return "docs"
    return "other"


def analyze_pr_tokens(base_ref: str = "origin/main") -> PRTokenReport:
    """Analyze token delta of the current branch compared to base_ref."""
    # Test if base_ref exists in git
    verify = subprocess.run(
        f"git rev-parse --verify {base_ref}",
        shell=True,
        capture_output=True,
        text=True,
    )
    if verify.returncode != 0:
        # Fallback to main or HEAD~1
        fallback = subprocess.run(
            "git rev-parse --verify main",
            shell=True,
            capture_output=True,
            text=True,
        )
        base_ref = "main" if fallback.returncode == 0 else "HEAD~1"

    # Get changed files
    res = subprocess.run(
        f"git diff --name-only {base_ref}...HEAD",
        shell=True,
        capture_output=True,
        text=True,
    )
    changed_files = [f.strip() for f in res.stdout.splitlines() if f.strip()]

    report = PRTokenReport(base_ref=base_ref)

    for file_path in changed_files:
        p = Path(file_path)
        cat = _get_category(file_path)

        # Get content before (bytes + replace: assets may contain legacy Latin-1)
        before_cmd = f"git show {base_ref}:{file_path}"
        before_res = subprocess.run(before_cmd, shell=True, capture_output=True)
        if before_res.returncode == 0:
            before_text = before_res.stdout.decode("utf-8", errors="replace")
            tokens_before = count_tokens(before_text).avg
        else:
            tokens_before = 0

        # Get content after
        tokens_after = 0
        if p.exists():
            try:
                content_after = p.read_text(encoding="utf-8", errors="replace")
                tokens_after = count_tokens(content_after).avg
            except Exception:
                tokens_after = 0
        else:
            # File might be deleted
            after_res = subprocess.run(
                f"git show HEAD:{file_path}", shell=True, capture_output=True
            )
            if after_res.returncode == 0:
                after_text = after_res.stdout.decode("utf-8", errors="replace")
                tokens_after = count_tokens(after_text).avg

        delta = tokens_after - tokens_before
        item = FileTokenDelta(
            path=file_path,
            category=cat,
            tokens_before=tokens_before,
            tokens_after=tokens_after,
            delta=delta,
        )
        report.files.append(item)
        report.total_delta += delta
        if cat == "code":
            report.code_delta += delta
        elif cat == "docs":
            report.docs_delta += delta
        elif cat == "lockfile":
            report.lockfile_delta += delta
        else:
            report.other_delta += delta

    return report
